<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs"> 
<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
    <meta http-equiv="Pragma" content="no-cache" /> 
    <meta http-equiv="Cache-Control" content="no-cache" /> 
    <meta name="description" content="National Library of Czech Republic digitized documents (periodical, monographs) access aplication." /> 
    <meta name="keywords" content="periodical, monograph, library, National Library of Czech Republic, book, publication, kramerius" /> 
    <meta name="AUTHOR" content="INCAD, www.incad.cz" /> 
    <link rel="icon" href="img/favicon.ico"/> 
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" /> 
    <link type="text/css" href="css/themes/base/ui.base.css" rel="stylesheet" /> 
    <link type="text/css" href="css/themes/base/ui.theme.css" rel="stylesheet" /> 
    <link type="text/css" href="css/themes/base/ui.dialog.css" rel="stylesheet" /> 
    <link type="text/css" href="css/themes/base/ui.slider.css" rel="stylesheet" /> 
    <link rel="stylesheet" href="css/dateAxisV.css" type="text/css"/> 
    <link rel="stylesheet" href="css/dtree.css" type="text/css"/> 
    <link rel="StyleSheet" href="css/styles.css" type="text/css"/> 
    <title>Kramerius 4</title> 
</head> 
<body> 
	<table style="width: 100%;">
		<tbody>
			<tr>
				<td align="center">
					<div class="ui-tabs ui-widget-content ui-corner-all facet"
						style="width: 600px;">
						<h2>Exportovany titul:Alternativni teorie jednani (CD_1)</h2>
					</div>
				</td>
			</tr>
			<tr>
				<td align="center">
					<div style="width: 600px">
					<ul
						class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
						<li style="width: 100%; height: 20px; text-align: center;" class="facetTitle ui-state-default ui-corner-top  ui-state-active">
						</li>
					</ul>
					<table width="600px">
						<thead style="border-bottom: dashed 1px; background-image: url('../../img/bg_processheader.png'); background-repeat: repeat-x;">
							<tr style="background-color: gray;">
								<td><strong>Soubor</strong></td>
							</tr>
						</thead>
							<tbody style="background-color: white;">
								<tr>
									<td><img src="img/pdf.png" /><a href="../Alternativní_1.pdf">Alternativní_1.pdf</a></td></tr>
								<tr>
									<td><img src="img/pdf.png" /><a href="../Alternativní_2.pdf">Alternativní_2.pdf</a></td></tr>
							</tbody>
					</table>
					</div>
				</td>
			</tr>
		</tbody>
	</table>

</body> 
</html>
