-- sekvence mapovani proces - token --
CREATE SEQUENCE PROCESS_2_TOKEN_ID_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 0;

-- mapovaci tabulka - session process  --
CREATE TABLE PROCESS_2_TOKEN(PROCESS_2_TOKEN_ID INT NOT NULL, 
	PROCESS_ID INT REFERENCES PROCESSES(PROCESS_ID), 
	TOKEN VARCHAR(255), 
	SESSION_KEYS_ID INT REFERENCES SESSION_KEYS(SESSION_KEYS_ID),
	PRIMARY KEY(PROCESS_2_TOKEN_ID));
	



