//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:18 AM CEST 
//


package org.kramerius.alto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A graphic used to separate blocks. Usually a line or rectangle. 
 * 
 * <p>Java class for GraphicalElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GraphicalElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.loc.gov/standards/alto/ns-v2#}BlockType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphicalElementType")
public class GraphicalElementType
    extends BlockType
{


}
