//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:41 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.periodical;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UniqueIdentifier" minOccurs="0"/&gt;
 *         &lt;element ref="{}PeriodicalItemIdentification"/&gt;
 *         &lt;element ref="{}CoreBibliographicDescriptionPeriodical" minOccurs="0"/&gt;
 *         &lt;element ref="{}ItemRepresentation" minOccurs="0"/&gt;
 *         &lt;element ref="{}PeriodicalInternalComponentPart" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}PeriodicalPage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" default="PeriodicalIssue"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="PeriodicalSupplement"/&gt;
 *             &lt;enumeration value="Appendix"/&gt;
 *             &lt;enumeration value="PeriodicalOtherItem"/&gt;
 *             &lt;enumeration value="PeriodicalIssue"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueIdentifier",
    "periodicalItemIdentification",
    "coreBibliographicDescriptionPeriodical",
    "itemRepresentation",
    "periodicalInternalComponentPart",
    "periodicalPage"
})
@XmlRootElement(name = "PeriodicalItem")
public class PeriodicalItem {

    @XmlElement(name = "UniqueIdentifier")
    protected UniqueIdentifier uniqueIdentifier;
    @XmlElement(name = "PeriodicalItemIdentification", required = true)
    protected PeriodicalItemIdentification periodicalItemIdentification;
    @XmlElement(name = "CoreBibliographicDescriptionPeriodical")
    protected CoreBibliographicDescriptionPeriodical coreBibliographicDescriptionPeriodical;
    @XmlElement(name = "ItemRepresentation")
    protected ItemRepresentation itemRepresentation;
    @XmlElement(name = "PeriodicalInternalComponentPart")
    protected List<PeriodicalInternalComponentPart> periodicalInternalComponentPart;
    @XmlElement(name = "PeriodicalPage")
    protected List<PeriodicalPage> periodicalPage;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIdentifier }
     *     
     */
    public UniqueIdentifier getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIdentifier }
     *     
     */
    public void setUniqueIdentifier(UniqueIdentifier value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the periodicalItemIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodicalItemIdentification }
     *     
     */
    public PeriodicalItemIdentification getPeriodicalItemIdentification() {
        return periodicalItemIdentification;
    }

    /**
     * Sets the value of the periodicalItemIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodicalItemIdentification }
     *     
     */
    public void setPeriodicalItemIdentification(PeriodicalItemIdentification value) {
        this.periodicalItemIdentification = value;
    }

    /**
     * Gets the value of the coreBibliographicDescriptionPeriodical property.
     * 
     * @return
     *     possible object is
     *     {@link CoreBibliographicDescriptionPeriodical }
     *     
     */
    public CoreBibliographicDescriptionPeriodical getCoreBibliographicDescriptionPeriodical() {
        return coreBibliographicDescriptionPeriodical;
    }

    /**
     * Sets the value of the coreBibliographicDescriptionPeriodical property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoreBibliographicDescriptionPeriodical }
     *     
     */
    public void setCoreBibliographicDescriptionPeriodical(CoreBibliographicDescriptionPeriodical value) {
        this.coreBibliographicDescriptionPeriodical = value;
    }

    /**
     * Gets the value of the itemRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRepresentation }
     *     
     */
    public ItemRepresentation getItemRepresentation() {
        return itemRepresentation;
    }

    /**
     * Sets the value of the itemRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRepresentation }
     *     
     */
    public void setItemRepresentation(ItemRepresentation value) {
        this.itemRepresentation = value;
    }

    /**
     * Gets the value of the periodicalInternalComponentPart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodicalInternalComponentPart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodicalInternalComponentPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodicalInternalComponentPart }
     * 
     * 
     */
    public List<PeriodicalInternalComponentPart> getPeriodicalInternalComponentPart() {
        if (periodicalInternalComponentPart == null) {
            periodicalInternalComponentPart = new ArrayList<PeriodicalInternalComponentPart>();
        }
        return this.periodicalInternalComponentPart;
    }

    /**
     * Gets the value of the periodicalPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodicalPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodicalPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodicalPage }
     * 
     * 
     */
    public List<PeriodicalPage> getPeriodicalPage() {
        if (periodicalPage == null) {
            periodicalPage = new ArrayList<PeriodicalPage>();
        }
        return this.periodicalPage;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "PeriodicalIssue";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
