//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:41 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.periodical;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UniqueIdentifier" minOccurs="0"/&gt;
 *         &lt;element ref="{}CoreBibliographicDescriptionPeriodical" minOccurs="0"/&gt;
 *         &lt;element ref="{}InternalComponentPartIdNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{}PageReference" minOccurs="0"/&gt;
 *         &lt;element ref="{}PageNumber"/&gt;
 *         &lt;element ref="{}Pages" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" default="Article"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Figure"/&gt;
 *             &lt;enumeration value="Abstract"/&gt;
 *             &lt;enumeration value="Introduction"/&gt;
 *             &lt;enumeration value="Reviews"/&gt;
 *             &lt;enumeration value="Dedication"/&gt;
 *             &lt;enumeration value="Chapter"/&gt;
 *             &lt;enumeration value="Article"/&gt;
 *             &lt;enumeration value="Table"/&gt;
 *             &lt;enumeration value="Illustration"/&gt;
 *             &lt;enumeration value="OtherNote"/&gt;
 *             &lt;enumeration value="Remark"/&gt;
 *             &lt;enumeration value="Photograph"/&gt;
 *             &lt;enumeration value="Bibliography"/&gt;
 *             &lt;enumeration value="Obituary"/&gt;
 *             &lt;enumeration value="Map"/&gt;
 *             &lt;enumeration value="TechnicalPlanScheme"/&gt;
 *             &lt;enumeration value="Debate"/&gt;
 *             &lt;enumeration value="OtherDocStrct"/&gt;
 *             &lt;enumeration value="EditorsNote"/&gt;
 *             &lt;enumeration value="Contributors"/&gt;
 *             &lt;enumeration value="Preface"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueIdentifier",
    "coreBibliographicDescriptionPeriodical",
    "internalComponentPartIdNumber",
    "pageReference",
    "pageNumber",
    "pages"
})
@XmlRootElement(name = "PeriodicalInternalComponentPart")
public class PeriodicalInternalComponentPart {

    @XmlElement(name = "UniqueIdentifier")
    protected UniqueIdentifier uniqueIdentifier;
    @XmlElement(name = "CoreBibliographicDescriptionPeriodical")
    protected CoreBibliographicDescriptionPeriodical coreBibliographicDescriptionPeriodical;
    @XmlElement(name = "InternalComponentPartIdNumber")
    protected InternalComponentPartIdNumber internalComponentPartIdNumber;
    @XmlElement(name = "PageReference")
    protected PageReference pageReference;
    @XmlElement(name = "PageNumber", required = true)
    protected PageNumber pageNumber;
    @XmlElement(name = "Pages")
    protected Pages pages;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIdentifier }
     *     
     */
    public UniqueIdentifier getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIdentifier }
     *     
     */
    public void setUniqueIdentifier(UniqueIdentifier value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the coreBibliographicDescriptionPeriodical property.
     * 
     * @return
     *     possible object is
     *     {@link CoreBibliographicDescriptionPeriodical }
     *     
     */
    public CoreBibliographicDescriptionPeriodical getCoreBibliographicDescriptionPeriodical() {
        return coreBibliographicDescriptionPeriodical;
    }

    /**
     * Sets the value of the coreBibliographicDescriptionPeriodical property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoreBibliographicDescriptionPeriodical }
     *     
     */
    public void setCoreBibliographicDescriptionPeriodical(CoreBibliographicDescriptionPeriodical value) {
        this.coreBibliographicDescriptionPeriodical = value;
    }

    /**
     * Gets the value of the internalComponentPartIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link InternalComponentPartIdNumber }
     *     
     */
    public InternalComponentPartIdNumber getInternalComponentPartIdNumber() {
        return internalComponentPartIdNumber;
    }

    /**
     * Sets the value of the internalComponentPartIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalComponentPartIdNumber }
     *     
     */
    public void setInternalComponentPartIdNumber(InternalComponentPartIdNumber value) {
        this.internalComponentPartIdNumber = value;
    }

    /**
     * Gets the value of the pageReference property.
     * 
     * @return
     *     possible object is
     *     {@link PageReference }
     *     
     */
    public PageReference getPageReference() {
        return pageReference;
    }

    /**
     * Sets the value of the pageReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageReference }
     *     
     */
    public void setPageReference(PageReference value) {
        this.pageReference = value;
    }

    /**
     * Gets the value of the pageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PageNumber }
     *     
     */
    public PageNumber getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageNumber }
     *     
     */
    public void setPageNumber(PageNumber value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Pages }
     *     
     */
    public Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pages }
     *     
     */
    public void setPages(Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Article";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
