//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:28 AM CEST 
//


package org.kramerius.mods;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageAuthorityAttributeDefinition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="languageAuthorityAttributeDefinition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="rfc3066"/&gt;
 *     &lt;enumeration value="iso639-2b"/&gt;
 *     &lt;enumeration value="iso639-3"/&gt;
 *     &lt;enumeration value="rfc4646"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "languageAuthorityAttributeDefinition")
@XmlEnum
public enum LanguageAuthorityAttributeDefinition {

    @XmlEnumValue("rfc3066")
    RFC_3066("rfc3066"),
    @XmlEnumValue("iso639-2b")
    ISO_639_2_B("iso639-2b"),
    @XmlEnumValue("iso639-3")
    ISO_639_3("iso639-3"),
    @XmlEnumValue("rfc4646")
    RFC_4646("rfc4646");
    private final String value;

    LanguageAuthorityAttributeDefinition(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageAuthorityAttributeDefinition fromValue(String v) {
        for (LanguageAuthorityAttributeDefinition c: LanguageAuthorityAttributeDefinition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
