//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:28 AM CEST 
//


package org.kramerius.mods;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for namePartDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="namePartDefinition"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.loc.gov/mods/v3&gt;xsString"&gt;
 *       &lt;attribute name="type" type="{http://www.loc.gov/mods/v3}namePartTypeAttributeDefinition" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "namePartDefinition")
public class NamePartDefinition
    extends XsString
{

    @XmlAttribute(name = "type")
    protected NamePartTypeAttributeDefinition type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link NamePartTypeAttributeDefinition }
     *     
     */
    public NamePartTypeAttributeDefinition getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamePartTypeAttributeDefinition }
     *     
     */
    public void setType(NamePartTypeAttributeDefinition value) {
        this.type = value;
    }

}
