//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:28 AM CEST 
//


package org.kramerius.mods;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stringPlusAuthorityPlusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stringPlusAuthorityPlusType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.loc.gov/mods/v3&gt;stringPlusAuthority"&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stringPlusAuthorityPlusType")
@XmlSeeAlso({
    StringPlusAuthorityPlusTypePlusDisplayLabel.class
})
public class StringPlusAuthorityPlusType
    extends StringPlusAuthority
{

    @XmlAttribute(name = "type")
    protected String type8;

    /**
     * Gets the value of the type8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType8() {
        return type8;
    }

    /**
     * Sets the value of the type8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType8(String value) {
        this.type8 = value;
    }

}
