//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:28 AM CEST 
//


package org.kramerius.mods;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for usageAttributeDefinition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="usageAttributeDefinition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="primary"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "usageAttributeDefinition")
@XmlEnum
public enum UsageAttributeDefinition {

    @XmlEnumValue("primary")
    PRIMARY("primary");
    private final String value;

    UsageAttributeDefinition(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UsageAttributeDefinition fromValue(String v) {
        for (UsageAttributeDefinition c: UsageAttributeDefinition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
