//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.08 at 09:44:21 AM CEST 
//


package org.kramerius.dc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oai_dcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oai_dcType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}creator"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}subject"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}publisher"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}contributor"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}date"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}type"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}format"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}identifier"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}source"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}language"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}relation"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}coverage"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}rights"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oai_dcType", namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/", propOrder = {
    "titleOrCreatorOrSubject"
})
public class OaiDcType {

    @XmlElementRefs({
        @XmlElementRef(name = "title", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "creator", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subject", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contributor", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "format", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identifier", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "source", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "language", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relation", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "coverage", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<ElementType>> titleOrCreatorOrSubject;

    /**
     * Gets the value of the titleOrCreatorOrSubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleOrCreatorOrSubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleOrCreatorOrSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<ElementType>> getTitleOrCreatorOrSubject() {
        if (titleOrCreatorOrSubject == null) {
            titleOrCreatorOrSubject = new ArrayList<JAXBElement<ElementType>>();
        }
        return this.titleOrCreatorOrSubject;
    }

}
