drop SEQUENCE SESSION_KEYS_ID_SEQUENCE;
drop SEQUENCE ACTIVE_USERS_ID_SEQUENCE_2_ROLES_ID_SEQUENCE;
drop SEQUENCE ACTIVE_USERS_ID_SEQUENCE;

drop table  SESSION_KEYS;
drop table ACTIVE_USERS_2_ROLES;
drop table ACTIVE_USERS;


