CREATE TABLE LOGGED_USERS(LOGGED_USERS_ID INT NOT NULL, 
        LOGGED_TIME TIMESTAMP,
        USER_KEY VARCHAR(255),
        LOGINNAME VARCHAR(1024),
        FIRSTNAME VARCHAR (1024),
        SURNAME VARCHAR(1024),
        PRIMARY KEY (LOGGED_USERS_ID));

CREATE SEQUENCE LOGGED_USERS_ID_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 0;

CREATE TABLE LOGGED_USERS_2_ROLES (
	LOGGED_USERS_2_ROLES_ID INT NOT NULL,
	LOGGED_USER_ID INT, 
	ROLE_ID INT,
	PRIMARY KEY(LOGGED_USERS_2_ROLES_ID));

CREATE SEQUENCE LOGGED_USERS_2_ROLES_ID_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 0;

ALTER TABLE LOGGED_USERS_2_ROLES ADD CONSTRAINT LOGGED_USERS_2_ROLES_LOGGED_USER_ID_FK FOREIGN KEY (LOGGED_USER_ID) REFERENCES LOGGED_USERS (LOGGED_USERS_ID);

ALTER TABLE LOGGED_USERS_2_ROLES ADD CONSTRAINT LOGGED_USERS_2_ROLES_ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES GROUP_ENTITY (GROUP_ID);

