drop table RIGHT_ENTITY;

drop table RIGHTS_CRITERIUM_ENTITY;

drop table CRITERIUM_PARAM_ENTITY;

drop view USER_GROUP_MAPPING;

drop view GROUP_USERS_MAPPING;

drop TABLE GROUP_USER_ASSOC;

drop TABLE USER_ENTITY;

drop table GROUP_ENTITY CASCADE;

drop SEQUENCE USER_ID_SEQUENCE;

drop SEQUENCE GROUP_ID_SEQUENCE;

drop SEQUENCE GROUP_USER_ASSOC_ID_SEQUENCE;

drop SEQUENCE CRIT_PARAM_ID_SEQUENCE;

drop SEQUENCE CRIT_ID_SEQUENCE;

drop SEQUENCE RIGHT_ID_SEQUENCE;

