//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ContributorSurname"/&gt;
 *         &lt;element ref="{}ContributorName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Role" default="Editor"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Proofreader"/&gt;
 *             &lt;enumeration value="BibliographicAntecedent"/&gt;
 *             &lt;enumeration value="DubiousAuthor"/&gt;
 *             &lt;enumeration value="MetalEngraver"/&gt;
 *             &lt;enumeration value="Originator"/&gt;
 *             &lt;enumeration value="PaperMaker"/&gt;
 *             &lt;enumeration value="FilmEditor"/&gt;
 *             &lt;enumeration value="BookDesigner"/&gt;
 *             &lt;enumeration value="Narrator"/&gt;
 *             &lt;enumeration value="Illuminator"/&gt;
 *             &lt;enumeration value="Commentator"/&gt;
 *             &lt;enumeration value="Typographer"/&gt;
 *             &lt;enumeration value="Corrector"/&gt;
 *             &lt;enumeration value="Dedicatee"/&gt;
 *             &lt;enumeration value="Engraver"/&gt;
 *             &lt;enumeration value="Recipient"/&gt;
 *             &lt;enumeration value="Lyricist"/&gt;
 *             &lt;enumeration value="Illustrator"/&gt;
 *             &lt;enumeration value="Interviewer"/&gt;
 *             &lt;enumeration value="Librettist"/&gt;
 *             &lt;enumeration value="WoodEngraver"/&gt;
 *             &lt;enumeration value="Calligrapher"/&gt;
 *             &lt;enumeration value="BookPlateDesigner"/&gt;
 *             &lt;enumeration value="Binder"/&gt;
 *             &lt;enumeration value="AuthorOfScreenplay"/&gt;
 *             &lt;enumeration value="Scenarist"/&gt;
 *             &lt;enumeration value="GraphicTechnician"/&gt;
 *             &lt;enumeration value="Editor"/&gt;
 *             &lt;enumeration value="Translator"/&gt;
 *             &lt;enumeration value="Performer"/&gt;
 *             &lt;enumeration value="Dedicator"/&gt;
 *             &lt;enumeration value="Rubricator"/&gt;
 *             &lt;enumeration value="TypeDesigner"/&gt;
 *             &lt;enumeration value="Assignee"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *             &lt;enumeration value="Licensee"/&gt;
 *             &lt;enumeration value="BindingDesigner"/&gt;
 *             &lt;enumeration value="Litographer"/&gt;
 *             &lt;enumeration value="Artist"/&gt;
 *             &lt;enumeration value="Interviewee"/&gt;
 *             &lt;enumeration value="Annotator"/&gt;
 *             &lt;enumeration value="Compositor"/&gt;
 *             &lt;enumeration value="Composer"/&gt;
 *             &lt;enumeration value="Photographer"/&gt;
 *             &lt;enumeration value="Cartographer"/&gt;
 *             &lt;enumeration value="Author"/&gt;
 *             &lt;enumeration value="Compiler"/&gt;
 *             &lt;enumeration value="AuthorOfIntroduction"/&gt;
 *             &lt;enumeration value="Etcher"/&gt;
 *             &lt;enumeration value="Secretary"/&gt;
 *             &lt;enumeration value="BookJacketDesigner"/&gt;
 *             &lt;enumeration value="CopyrightHolder"/&gt;
 *             &lt;enumeration value="Honoree"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contributorSurname",
    "contributorName"
})
@XmlRootElement(name = "Contributor")
public class Contributor {

    @XmlElement(name = "ContributorSurname", required = true)
    protected ContributorSurname contributorSurname;
    @XmlElement(name = "ContributorName")
    protected List<ContributorName> contributorName;
    @XmlAttribute(name = "Role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String role;

    /**
     * Gets the value of the contributorSurname property.
     * 
     * @return
     *     possible object is
     *     {@link ContributorSurname }
     *     
     */
    public ContributorSurname getContributorSurname() {
        return contributorSurname;
    }

    /**
     * Sets the value of the contributorSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContributorSurname }
     *     
     */
    public void setContributorSurname(ContributorSurname value) {
        this.contributorSurname = value;
    }

    /**
     * Gets the value of the contributorName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributorName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributorName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContributorName }
     * 
     * 
     */
    public List<ContributorName> getContributorName() {
        if (contributorName == null) {
            contributorName = new ArrayList<ContributorName>();
        }
        return this.contributorName;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        if (role == null) {
            return "Editor";
        } else {
            return role;
        }
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
