//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UniqueIdentifier" minOccurs="0"/&gt;
 *         &lt;element ref="{}MonographOwner" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}MonographBibliographicRecord"/&gt;
 *         &lt;element ref="{}MonographPage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}MonographComponentPart" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}MonographUnit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}TechnicalDescription" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueIdentifier",
    "monographOwner",
    "monographBibliographicRecord",
    "monographPage",
    "monographComponentPart",
    "monographUnit",
    "technicalDescription"
})
@XmlRootElement(name = "Monograph")
public class Monograph {

    @XmlElement(name = "UniqueIdentifier")
    protected UniqueIdentifier uniqueIdentifier;
    @XmlElement(name = "MonographOwner", required = true)
    protected List<MonographOwner> monographOwner;
    @XmlElement(name = "MonographBibliographicRecord", required = true)
    protected MonographBibliographicRecord monographBibliographicRecord;
    @XmlElement(name = "MonographPage")
    protected List<MonographPage> monographPage;
    @XmlElement(name = "MonographComponentPart")
    protected List<MonographComponentPart> monographComponentPart;
    @XmlElement(name = "MonographUnit")
    protected List<MonographUnit> monographUnit;
    @XmlElement(name = "TechnicalDescription")
    protected TechnicalDescription technicalDescription;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIdentifier }
     *     
     */
    public UniqueIdentifier getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIdentifier }
     *     
     */
    public void setUniqueIdentifier(UniqueIdentifier value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the monographOwner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monographOwner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonographOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonographOwner }
     * 
     * 
     */
    public List<MonographOwner> getMonographOwner() {
        if (monographOwner == null) {
            monographOwner = new ArrayList<MonographOwner>();
        }
        return this.monographOwner;
    }

    /**
     * Gets the value of the monographBibliographicRecord property.
     * 
     * @return
     *     possible object is
     *     {@link MonographBibliographicRecord }
     *     
     */
    public MonographBibliographicRecord getMonographBibliographicRecord() {
        return monographBibliographicRecord;
    }

    /**
     * Sets the value of the monographBibliographicRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonographBibliographicRecord }
     *     
     */
    public void setMonographBibliographicRecord(MonographBibliographicRecord value) {
        this.monographBibliographicRecord = value;
    }

    /**
     * Gets the value of the monographPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monographPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonographPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonographPage }
     * 
     * 
     */
    public List<MonographPage> getMonographPage() {
        if (monographPage == null) {
            monographPage = new ArrayList<MonographPage>();
        }
        return this.monographPage;
    }

    /**
     * Gets the value of the monographComponentPart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monographComponentPart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonographComponentPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonographComponentPart }
     * 
     * 
     */
    public List<MonographComponentPart> getMonographComponentPart() {
        if (monographComponentPart == null) {
            monographComponentPart = new ArrayList<MonographComponentPart>();
        }
        return this.monographComponentPart;
    }

    /**
     * Gets the value of the monographUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monographUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonographUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonographUnit }
     * 
     * 
     */
    public List<MonographUnit> getMonographUnit() {
        if (monographUnit == null) {
            monographUnit = new ArrayList<MonographUnit>();
        }
        return this.monographUnit;
    }

    /**
     * Gets the value of the technicalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalDescription }
     *     
     */
    public TechnicalDescription getTechnicalDescription() {
        return technicalDescription;
    }

    /**
     * Sets the value of the technicalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalDescription }
     *     
     */
    public void setTechnicalDescription(TechnicalDescription value) {
        this.technicalDescription = value;
    }

}
