//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Title"/&gt;
 *         &lt;element ref="{}Creator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Contributor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}GMD"/&gt;
 *         &lt;element ref="{}Publisher" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Printer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}PhysicalDescription"/&gt;
 *         &lt;element ref="{}ISBN" minOccurs="0"/&gt;
 *         &lt;element ref="{}Series" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Language" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}Subject" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Keyword" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Accessibility" minOccurs="0"/&gt;
 *         &lt;element ref="{}Notes" minOccurs="0"/&gt;
 *         &lt;element ref="{}Annotation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "creator",
    "contributor",
    "gmd",
    "publisher",
    "printer",
    "physicalDescription",
    "isbn",
    "series",
    "language",
    "subject",
    "keyword",
    "accessibility",
    "notes",
    "annotation"
})
@XmlRootElement(name = "MonographBibliographicRecord")
public class MonographBibliographicRecord {

    @XmlElement(name = "Title", required = true)
    protected Title title;
    @XmlElement(name = "Creator")
    protected List<Creator> creator;
    @XmlElement(name = "Contributor")
    protected List<Contributor> contributor;
    @XmlElement(name = "GMD", required = true)
    protected GMD gmd;
    @XmlElement(name = "Publisher")
    protected List<Publisher> publisher;
    @XmlElement(name = "Printer")
    protected List<Printer> printer;
    @XmlElement(name = "PhysicalDescription", required = true)
    protected PhysicalDescription physicalDescription;
    @XmlElement(name = "ISBN")
    protected ISBN isbn;
    @XmlElement(name = "Series")
    protected List<Series> series;
    @XmlElement(name = "Language", required = true)
    protected List<Language> language;
    @XmlElement(name = "Subject")
    protected List<Subject> subject;
    @XmlElement(name = "Keyword")
    protected List<Keyword> keyword;
    @XmlElement(name = "Accessibility")
    protected Accessibility accessibility;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlElement(name = "Annotation")
    protected Annotation annotation;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Creator }
     * 
     * 
     */
    public List<Creator> getCreator() {
        if (creator == null) {
            creator = new ArrayList<Creator>();
        }
        return this.creator;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributor }
     * 
     * 
     */
    public List<Contributor> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<Contributor>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the gmd property.
     * 
     * @return
     *     possible object is
     *     {@link GMD }
     *     
     */
    public GMD getGMD() {
        return gmd;
    }

    /**
     * Sets the value of the gmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMD }
     *     
     */
    public void setGMD(GMD value) {
        this.gmd = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publisher }
     * 
     * 
     */
    public List<Publisher> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<Publisher>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the printer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the printer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrinter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Printer }
     * 
     * 
     */
    public List<Printer> getPrinter() {
        if (printer == null) {
            printer = new ArrayList<Printer>();
        }
        return this.printer;
    }

    /**
     * Gets the value of the physicalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalDescription }
     *     
     */
    public PhysicalDescription getPhysicalDescription() {
        return physicalDescription;
    }

    /**
     * Sets the value of the physicalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalDescription }
     *     
     */
    public void setPhysicalDescription(PhysicalDescription value) {
        this.physicalDescription = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link ISBN }
     *     
     */
    public ISBN getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISBN }
     *     
     */
    public void setISBN(ISBN value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the series property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Series }
     * 
     * 
     */
    public List<Series> getSeries() {
        if (series == null) {
            series = new ArrayList<Series>();
        }
        return this.series;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * 
     * 
     */
    public List<Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getSubject() {
        if (subject == null) {
            subject = new ArrayList<Subject>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keyword }
     * 
     * 
     */
    public List<Keyword> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<Keyword>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the accessibility property.
     * 
     * @return
     *     possible object is
     *     {@link Accessibility }
     *     
     */
    public Accessibility getAccessibility() {
        return accessibility;
    }

    /**
     * Sets the value of the accessibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accessibility }
     *     
     */
    public void setAccessibility(Accessibility value) {
        this.accessibility = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation }
     *     
     */
    public Annotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation }
     *     
     */
    public void setAnnotation(Annotation value) {
        this.annotation = value;
    }

}
