//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UniqueIdentifier" minOccurs="0"/&gt;
 *         &lt;element ref="{}MonographComponentPartIdentification" minOccurs="0"/&gt;
 *         &lt;element ref="{}Title" minOccurs="0"/&gt;
 *         &lt;element ref="{}Creator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Contributor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Language" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}Subject" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Keyword" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Accessibility" minOccurs="0"/&gt;
 *         &lt;element ref="{}Notes" minOccurs="0"/&gt;
 *         &lt;element ref="{}PageReference"/&gt;
 *         &lt;element ref="{}PageNumber"/&gt;
 *         &lt;element ref="{}Pages" minOccurs="0"/&gt;
 *         &lt;element ref="{}MonographComponentPartRepresentation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" default="Article"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Figure"/&gt;
 *             &lt;enumeration value="Abstract"/&gt;
 *             &lt;enumeration value="Introduction"/&gt;
 *             &lt;enumeration value="Reviews"/&gt;
 *             &lt;enumeration value="Dedication"/&gt;
 *             &lt;enumeration value="Chapter"/&gt;
 *             &lt;enumeration value="Article"/&gt;
 *             &lt;enumeration value="Table"/&gt;
 *             &lt;enumeration value="Illustration"/&gt;
 *             &lt;enumeration value="OtherNote"/&gt;
 *             &lt;enumeration value="Remark"/&gt;
 *             &lt;enumeration value="Study"/&gt;
 *             &lt;enumeration value="Photograph"/&gt;
 *             &lt;enumeration value="Bibliography"/&gt;
 *             &lt;enumeration value="Obituary"/&gt;
 *             &lt;enumeration value="Map"/&gt;
 *             &lt;enumeration value="TechnicalPlanScheme"/&gt;
 *             &lt;enumeration value="Debate"/&gt;
 *             &lt;enumeration value="OtherDocStrct"/&gt;
 *             &lt;enumeration value="EditorsNote"/&gt;
 *             &lt;enumeration value="Contributors"/&gt;
 *             &lt;enumeration value="Preface"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueIdentifier",
    "monographComponentPartIdentification",
    "title",
    "creator",
    "contributor",
    "language",
    "subject",
    "keyword",
    "accessibility",
    "notes",
    "pageReference",
    "pageNumber",
    "pages",
    "monographComponentPartRepresentation"
})
@XmlRootElement(name = "MonographComponentPart")
public class MonographComponentPart {

    @XmlElement(name = "UniqueIdentifier")
    protected UniqueIdentifier uniqueIdentifier;
    @XmlElement(name = "MonographComponentPartIdentification")
    protected MonographComponentPartIdentification monographComponentPartIdentification;
    @XmlElement(name = "Title")
    protected Title title;
    @XmlElement(name = "Creator")
    protected List<Creator> creator;
    @XmlElement(name = "Contributor")
    protected List<Contributor> contributor;
    @XmlElement(name = "Language", required = true)
    protected List<Language> language;
    @XmlElement(name = "Subject")
    protected List<Subject> subject;
    @XmlElement(name = "Keyword")
    protected List<Keyword> keyword;
    @XmlElement(name = "Accessibility")
    protected Accessibility accessibility;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlElement(name = "PageReference", required = true)
    protected PageReference pageReference;
    @XmlElement(name = "PageNumber", required = true)
    protected PageNumber pageNumber;
    @XmlElement(name = "Pages")
    protected Pages pages;
    @XmlElement(name = "MonographComponentPartRepresentation")
    protected MonographComponentPartRepresentation monographComponentPartRepresentation;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIdentifier }
     *     
     */
    public UniqueIdentifier getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIdentifier }
     *     
     */
    public void setUniqueIdentifier(UniqueIdentifier value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the monographComponentPartIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link MonographComponentPartIdentification }
     *     
     */
    public MonographComponentPartIdentification getMonographComponentPartIdentification() {
        return monographComponentPartIdentification;
    }

    /**
     * Sets the value of the monographComponentPartIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonographComponentPartIdentification }
     *     
     */
    public void setMonographComponentPartIdentification(MonographComponentPartIdentification value) {
        this.monographComponentPartIdentification = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Creator }
     * 
     * 
     */
    public List<Creator> getCreator() {
        if (creator == null) {
            creator = new ArrayList<Creator>();
        }
        return this.creator;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributor }
     * 
     * 
     */
    public List<Contributor> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<Contributor>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * 
     * 
     */
    public List<Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getSubject() {
        if (subject == null) {
            subject = new ArrayList<Subject>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keyword }
     * 
     * 
     */
    public List<Keyword> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<Keyword>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the accessibility property.
     * 
     * @return
     *     possible object is
     *     {@link Accessibility }
     *     
     */
    public Accessibility getAccessibility() {
        return accessibility;
    }

    /**
     * Sets the value of the accessibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accessibility }
     *     
     */
    public void setAccessibility(Accessibility value) {
        this.accessibility = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the pageReference property.
     * 
     * @return
     *     possible object is
     *     {@link PageReference }
     *     
     */
    public PageReference getPageReference() {
        return pageReference;
    }

    /**
     * Sets the value of the pageReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageReference }
     *     
     */
    public void setPageReference(PageReference value) {
        this.pageReference = value;
    }

    /**
     * Gets the value of the pageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PageNumber }
     *     
     */
    public PageNumber getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageNumber }
     *     
     */
    public void setPageNumber(PageNumber value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Pages }
     *     
     */
    public Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pages }
     *     
     */
    public void setPages(Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the monographComponentPartRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link MonographComponentPartRepresentation }
     *     
     */
    public MonographComponentPartRepresentation getMonographComponentPartRepresentation() {
        return monographComponentPartRepresentation;
    }

    /**
     * Sets the value of the monographComponentPartRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonographComponentPartRepresentation }
     *     
     */
    public void setMonographComponentPartRepresentation(MonographComponentPartRepresentation value) {
        this.monographComponentPartRepresentation = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Article";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
