//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UniqueIdentifier" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}PartInImage"/&gt;
 *           &lt;element ref="{}PartInText"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}TechnicalDescription" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueIdentifier",
    "partInImage",
    "partInText",
    "technicalDescription"
})
@XmlRootElement(name = "MonographComponentPartRepresentation")
public class MonographComponentPartRepresentation {

    @XmlElement(name = "UniqueIdentifier")
    protected UniqueIdentifier uniqueIdentifier;
    @XmlElement(name = "PartInImage")
    protected PartInImage partInImage;
    @XmlElement(name = "PartInText")
    protected PartInText partInText;
    @XmlElement(name = "TechnicalDescription")
    protected TechnicalDescription technicalDescription;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIdentifier }
     *     
     */
    public UniqueIdentifier getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIdentifier }
     *     
     */
    public void setUniqueIdentifier(UniqueIdentifier value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the partInImage property.
     * 
     * @return
     *     possible object is
     *     {@link PartInImage }
     *     
     */
    public PartInImage getPartInImage() {
        return partInImage;
    }

    /**
     * Sets the value of the partInImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartInImage }
     *     
     */
    public void setPartInImage(PartInImage value) {
        this.partInImage = value;
    }

    /**
     * Gets the value of the partInText property.
     * 
     * @return
     *     possible object is
     *     {@link PartInText }
     *     
     */
    public PartInText getPartInText() {
        return partInText;
    }

    /**
     * Sets the value of the partInText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartInText }
     *     
     */
    public void setPartInText(PartInText value) {
        this.partInText = value;
    }

    /**
     * Gets the value of the technicalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalDescription }
     *     
     */
    public TechnicalDescription getTechnicalDescription() {
        return technicalDescription;
    }

    /**
     * Sets the value of the technicalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalDescription }
     *     
     */
    public void setTechnicalDescription(TechnicalDescription value) {
        this.technicalDescription = value;
    }

}
