//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PreservationStateOfArt"/&gt;
 *         &lt;element ref="{}PreservationTreatment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preservationStateOfArt",
    "preservationTreatment"
})
@XmlRootElement(name = "PreservationStatus")
public class PreservationStatus {

    @XmlElement(name = "PreservationStateOfArt", required = true)
    protected PreservationStateOfArt preservationStateOfArt;
    @XmlElement(name = "PreservationTreatment")
    protected PreservationTreatment preservationTreatment;

    /**
     * Gets the value of the preservationStateOfArt property.
     * 
     * @return
     *     possible object is
     *     {@link PreservationStateOfArt }
     *     
     */
    public PreservationStateOfArt getPreservationStateOfArt() {
        return preservationStateOfArt;
    }

    /**
     * Sets the value of the preservationStateOfArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreservationStateOfArt }
     *     
     */
    public void setPreservationStateOfArt(PreservationStateOfArt value) {
        this.preservationStateOfArt = value;
    }

    /**
     * Gets the value of the preservationTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link PreservationTreatment }
     *     
     */
    public PreservationTreatment getPreservationTreatment() {
        return preservationTreatment;
    }

    /**
     * Sets the value of the preservationTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreservationTreatment }
     *     
     */
    public void setPreservationTreatment(PreservationTreatment value) {
        this.preservationTreatment = value;
    }

}
