//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.02 at 09:48:34 AM CEST 
//


package com.qbizm.kramerius.imp.jaxb.monograph;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}UDC"/&gt;
 *         &lt;element ref="{}DDC"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "udc",
    "ddc"
})
@XmlRootElement(name = "Subject")
public class Subject {

    @XmlElement(name = "UDC", required = true)
    protected UDC udc;
    @XmlElement(name = "DDC", required = true)
    protected DDC ddc;

    /**
     * Gets the value of the udc property.
     * 
     * @return
     *     possible object is
     *     {@link UDC }
     *     
     */
    public UDC getUDC() {
        return udc;
    }

    /**
     * Sets the value of the udc property.
     * 
     * @param value
     *     allowed object is
     *     {@link UDC }
     *     
     */
    public void setUDC(UDC value) {
        this.udc = value;
    }

    /**
     * Gets the value of the ddc property.
     * 
     * @return
     *     possible object is
     *     {@link DDC }
     *     
     */
    public DDC getDDC() {
        return ddc;
    }

    /**
     * Sets the value of the ddc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDC }
     *     
     */
    public void setDDC(DDC value) {
        this.ddc = value;
    }

}
