plugins {
    id 'java-library'
    id 'org.ceskaexpedice.processplatform.process' version '1.0.6'
}

description "KAPP sync"

processPlugin {
    spiImplementation='org.kramerius.plugin.KappSyncSPI'
    profiles = [
            [profileId: "kapp-sync",description: "KAPP sync",jvmArgs: ["-Xms1g","-Xmx32g"]]
    ]
    excludeDependencies = [
        'com.sun.jersey',
        'javax.ws.rs'
    ]
}

dependencies{
    implementation project(':processes:licenses-sync')
    implementation "org.ceskaexpedice:process-api:${processapiversion}"
}

